menu:
  - { name: "people", url: "/people" }
  - { name: "publications", url: "/publications" }
  - { name: "contact", url: "/contact" }

people:
  - {
      name: "Cynthia Rudin ",
      title: "Principal Investigator ",
      department: "Earl D. McLean, Jr. Professor of Computer Science, Electrical and Computer Engineering, Statistical Science, Mathematics, and Biostatistics & Bioinformatics",
      institution: "Duke University",
      institution_address: "1Research Drive Durham NC, 27708 USA",
      email: "hello@university.edu",
      office: "LSRC D342",
      image: "assets/img/people/cynthia_rudin.jpeg",
      url: "https://users.cs.duke.edu/~cynthia/",
    }
  - {
      name: "Joseph Yuan-Chieh Lo",
      title: "Principal Investigator",
      department: "Radiology, Biomedical Engineering, Electrical and Computer Engineering, Duke Cancer Institute",
      institution: "Duke University",
      institution_address: "2424 Erwin Road, Suite 302, Ravin Advanced Imaging Labs, Durham, NC 27705",
      email: "hello@university.edu",
      office: "Science Building 505",
      image: "assets/img/people/joseph_lo.jpeg",
      url: "https://radiology.duke.edu/profile/joseph-yuan-chieh-lo",
    }
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "1 Main Street, Canada",
      email: "hello@university.edu",
      image: "assets/img/people/alina_jade_barnett.jpeg",
      url: "https://alinajadebarnett.github.io/",
    }
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "1 Main Street, Canada",
      email: "hello@university.edu",
      image: "assets/img/people/alina_jade_barnett.jpeg",
      url: "https://alinajadebarnett.github.io/",
    }
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "1 Main Street, Canada",
      email: "hello@university.edu",
      image: "assets/img/people/alina_jade_barnett.jpeg",
      url: "https://alinajadebarnett.github.io/",
    }
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "1 Main Street, Canada",
      email: "hello@university.edu",
      image: "assets/img/people/alina_jade_barnett.jpeg",
      url: "https://alinajadebarnett.github.io/",
    }
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "1 Main Street, Canada",
      email: "hello@university.edu",
      image: "assets/img/people/alina_jade_barnett.jpeg",
      url: "https://alinajadebarnett.github.io/",
    }

courses:
  - { name: "Vector Calculus", url: "vector-calculus" }
  - { name: "Quantum Mechanics", url: "quantum-mechanics" }
  - { name: "Stellar Structures", url: "stellar-structures" }

# social:
#   - { icon: "github", link: "https://github.com/LeNPaul" }
#   - { icon: "twitter", link: "https://twitter.com/paululele" }
#   - { icon: "instagram", link: "https://instagram.com/paululele" }
#   - { icon: "linkedin", link: "https://linkedin.com/in/lenpaul" }

contacts:
  - {
      name: "Dr. Alina Jade Barnett",
      title: "Title",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Dr, Durham, NC 27705, United States",
      phone: "(000) 000-0000",
      email: "hello@university.edu",
      office: "Office Location",
      image: "assets/img/contact.jpg",
    }
