menu:
  - { name: "people", url: "/people" }
  - { name: "publications", url: "/publications" }
  - { name: "contact", url: "/contact" }

people:
  - {
      name: "Cynthia Rudin ",
      title: "Principal Investigator ",
      department: "Earl D. McLean, Jr. Professor of Computer Science, Electrical and Computer Engineering, Statistical Science, Mathematics, and Biostatistics & Bioinformatics",
      institution: "Duke University",
      institution_address: "Research Drive, Durham NC, 27708 USA",
      email: "cynthia@cs.duke.edu",
      emailimg: assets/img/emails/cynthia_rudin_email.jpeg
      office: "LSRC D342",
      image: "assets/img/people/cynthia_rudin.jpeg",
      url: "https://users.cs.duke.edu/~cynthia/",
    }
  - {
      name: "Joseph Yuan-Chieh Lo",
      title: "Principal Investigator",
      department: "Radiology, Biomedical Engineering, Electrical and Computer Engineering, Duke Cancer Institute",
      institution: "Duke University",
      institution_address: "2424 Erwin Road, Suite 302, Ravin Advanced Imaging Labs, Durham, NC 27705",
      email: "joseph.lo@duke.edu",
      emailimg: "",
      office: "Science Building 505",
      image: "assets/img/people/joseph_lo.jpeg",
      url: "https://radiology.duke.edu/profile/joseph-yuan-chieh-lo",
    }
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "alina.barnett@duke.edu",
      emailimg: "",
      image: "assets/img/people/alina_jade_barnett.jpeg",
      url: "https://alinajadebarnett.github.io/",
    }
  - {
      name: "Fides Schwartz",
      title: "--",
      department: "--",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "fidesreginadorotheaann.schwartz@duke.edu",
      emailimg: "",
      image: "assets/img/people/fides_schwartz.jpeg",
    }
  - {
      name: "Chaofan Chen",
      title: "Assistant Professor in Computer Science",
      department: "Computer Science",
      institution: "University of Maine",
      institution_address: "5711 Boardman Hall, Room 348, Orono, ME 04469",
      email: "chaofan.chen@maine.edu",
      emailimg: "",
      office: "233 Boardman Hall",
      image: "assets/img/people/chaofan_chen.jpeg",
      url: "https://umaine.edu/scis/people/chaofan-chen/",
    }
  - {
      name: "Vaibhav Sharma",
      title: "Undergraduate Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "vaibhav.sharma@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Jessie Ou",
      title: "Undergraduate Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "--",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Anika Mitra",
      title: "Undergraduate Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "anika.mitra@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Jon Donnelly",
      title: "PhD Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "jon.donnelly@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Luke Moffett",
      title: "PhD Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "luke.moffett@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Julia Yang",
      title: "Research Assistant",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "julia.yang@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Sangwook Cheon",
      title: "Undergraduate Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "sangwook.cheon@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }
  - {
      name: "Giyoung Kim",
      title: "Undergraduate Student",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Drive, Durham, NC 27708-0129",
      email: "giyoung.kim@duke.edu",
      emailimg: "",
      image: "assets/img/people/sample.jpeg",
    }



courses:
  - { name: "Vector Calculus", url: "vector-calculus" }
  - { name: "Quantum Mechanics", url: "quantum-mechanics" }
  - { name: "Stellar Structures", url: "stellar-structures" }

# social:
#   - { icon: "github", link: "https://github.com/LeNPaul" }
#   - { icon: "twitter", link: "https://twitter.com/paululele" }
#   - { icon: "instagram", link: "https://instagram.com/paululele" }
#   - { icon: "linkedin", link: "https://linkedin.com/in/lenpaul" }

contacts:
  - {
      name: "Alina Jade Barnett",
      title: "Post-doctoral Fellow",
      department: "Computer Science",
      institution: "Duke University",
      institution_address: "308 Research Dr, Durham, NC 27705, United States",
      phone: "(000) 000-0000",
      email: "hello@university.edu",
      office: "Office Location",
      image: "assets/img/people/alina_jade_barnett.jpeg",
    }
